config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}

devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}  


  namespace :admin do
    get 'homes/top'
    resources :spaces
    resources :users
    resources :reservations, only: [:index, :show]
  end
  
  
# public_user
  get "/homes/reject" => "homes#reject", as: 'homes_reject'
  get "/users/quit" => "users#quit", as: 'users_quit'
  patch "/users/out" => "users#out", as: 'users_out' 
  root to: 'homes#top'
  resources :users, except: [:edit]
  resources :reservations # , except: [:show]
  post "/reservations/confirm" => "reservations#confirm", as: 'reservations_confirm'
  get 'homes/about'
end

app/models/space.rb
class Space < ApplicationRecord
    has_many :reservations
end

app/controllers/admin/spaces_controller.rb
class Admin::SpacesController < ApplicationController
  def index
    @space = Space.new
    @spaces = Space.all
  end

  def show
  end

  def edit
    @space = Space.find(params[:id])
  end

  def new
  end
  
  def create
    @space = Space.all
    @space = Space.new(space_params)
    @space.save
    redirect_to admin_spaces_path
  end
  
  
  def update
    @space = Space.find(params[:id])
    @space.update(space_params)
    redirect_to admin_spaces_path
  end

  private

  def space_params
    params.require(:space).permit(:name, :introduction )
  end
  
end

app/helpers/admin/spaces_helper.rb
module Admin::SpacesHelper
end

app/views/admin/spaces/edit.html.erb
<div class="mt-5 ml-5 h3">席情報編集</div>

<div class="container container-m py-3 ml-4 h5">
  <%= form_with model: @space, url:admin_space_path, local:true do |f| %>
  <p class="h5"> 名前<%= f.text_field :name %></p>
  <p class="h5"> 説明<%= f.text_field :introduction %></p>
  <p class="h5"><%= f.submit "更新" %></p>
  <% end %>
</div>

app/views/admin/spaces/index.html.erb
<div class="py-3 ml-5 h3">席情報</div>

<div class="col-md-8 offset-md-1">
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th class="text-center">名前</th>
      <th class="text-center">説明</th>
      <th class="text-center"></th>
    </tr>
  </thead>
  
  
  <%= form_with model: @space, url:admin_spaces_path, local:true do |f| %>
    <tr>
      <th class="text-center"><%= f.text_field :name %></th>
      <th class="text-center"><%= f.text_field :introduction %></th>
      <th class="text-center"><%= f.submit "新規登録" %></th>
    </tr> 
  <% end %>

  <tbody>
    <% @spaces.each do |space| %>
     <tr>
      <td class="text-center"><%= space.name %></td>
      <td class="text-center"><%= space.introduction %></td>
      <td class="text-center"><%= link_to "編集する", edit_admin_space_path(space) %></td>
     </tr>
    <% end %>

  </tbody>
  </table>
    </div>

app/views/admin/spaces/new.html.erb
<h1>Admin::Spaces#new</h1>
<p>Find me in app/views/admin/spaces/new.html.erb</p>

app/views/admin/spaces/show.html.erb
<h1>Admin::Spaces#show</h1>
<p>Find me in app/views/admin/spaces/show.html.erb</p>