config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}

devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}  


  namespace :admin do
    get 'homes/top'
    resources :spaces
    resources :users
    resources :reservations, only: [:index, :show]
  end
  
  
# public_user
  get "/homes/reject" => "homes#reject", as: 'homes_reject'
  get "/users/quit" => "users#quit", as: 'users_quit'
  patch "/users/out" => "users#out", as: 'users_out' 
  root to: 'homes#top'
  resources :users, except: [:edit]
  resources :reservations # , except: [:show]
  post "/reservations/confirm" => "reservations#confirm", as: 'reservations_confirm'
  get 'homes/about'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :space, optional: true
    def booked_time
        start_date..end_date
    end
    validates :space_id, presence: true
    validates :start_date, presence: true
    validate :check_reserved_date?, on: :check_reserved
    validate :check_reserved_space
    def check_reserved_date?
      # binding.irb
      if !(Date.today <= start_date.to_date && DateTime.current.hour * 100 + DateTime.current.min <= start_time.hour * 100 + start_time.min)
        errors.add(:start_date, "は今の時刻よりもあとに設定しましょう。")
      end
    end

    validate :check_reserved_time?, on: :check_reserved
    def check_reserved_time?
      # binding.irb
      # if !(self.start_date < self.end_date) || !(self.start_date = self.end_date && self.start_time < self.end_time)
      #   errors.add(:start_time, "有効な時間を設定してください。")
      # end
      
      
      if self.start_date > self.end_date
        errors.add(:start_time, "有効なDateを設定してください。")
      end
      
      if self.start_time > self.end_time
        errors.add(:start_time, "有効なTimeを設定してください。")
      end
      
    end
    
    def check_reserved_space
      space = Reservation.where(space_id: self.space_id)
      
      # TODO : GET DATE BETWEEN
      if space.where('start_time >= ? AND ? < end_time', self.start_time, self.start_time).present?
        errors.add(:start_time, "予約済です。")
      end
      if space.where('start_time < ? AND ? <= end_time', self.end_time, self.end_time).present?
        errors.add(:end_time, "予約済です。")
      end      
    end




end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  def index
    @reservations = Reservation.page(params[:page]).reverse_order
    # binding.pry
  end

  def show
    @reservations = Reservation.where(params[:user_id])
    # @user = params[:user_id].....
    # binding.pry
    # @reservation = Reservation.find(params[:id])
    # @reservations = Reservation.where(user_id: @reservation)
  end
  
  
  

  private
  def reservation_params
    params.require(:reservation).permit(:user_id, :space_id, :start_date, :start_time, :end_date, :end_time)
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
     before_action :authenticate_user!
     before_action :reject_reservation
  
  def index
    @reservations = Reservation.where(user_id: current_user.id).page(params[:page]).reverse_order
  end
  
  def new
    @reservation = Reservation.new
    reservation_view_make
  end
  
    
    def confirm
      @reservation = Reservation.new(reservation_params)
    if params[:reservation][:select_space] =="1" 
      @reservation.space_id = "1"
    elsif params[:reservation][:select_space]  == "2"
      @reservation.space_id = "2"
    elsif params[:reservation][:select_space]  == "3"
      @reservation.space_id = "3"
    elsif params[:reservation][:select_space]  == "4"
      @reservation.space_id = "4"
    end
    
    # @reservation.start_time.change(day: @reservation.start_date)
    # @reservation.end_time.change(day: @reservation.end_date)
    
    end
  
  
  def create
    @reservation = Reservation.all
    @reservation = Reservation.new(reservation_params)
    if @reservation.save(context: :check_reserved)
      redirect_to new_reservation_path
    else
      reservation_view_make
      render :new
    end
  end
  
  def show
    redirect_to new_reservation_path
  end
  
  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to reservations_path
  end
  
  private
  def reservation_params
    params.require(:reservation).permit(:user_id, :space_id, :start_date, :start_time, :end_date, :end_time)
  end
  
  def reservation_view_make
    @reservation_dates = []
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    now = Time.now
    one_week_later = now.since(6.days).to_date
    today = now.to_date
    (today..one_week_later).each do |date|
      @reservation_dates << [ date.strftime(("%Y年%-m月%-d日 (#{wd[date.wday]})")), date.strftime(("%Y-%m-%d")) ]
    end
    spaces = Space.all
    @timelines = []
    @space_statuses = []
    # 全スペースの数を数え、それだけ繰り返す
    spaces.size.times do |i|
      @space_statuses << []
    end
    if params[:now].present? && params[:type] == "next"
      @now = params[:now]
      @now = Time.parse(@now) +60*60*11
    elsif params[:now].present? && params[:type] == "back"
      @now = params[:now]
      @now = Time.parse(@now) -60*60*11
    else
      @now = Time.current
    end
    
    range = 1..23
    range.each do |i|
      time = @now - @now.min*60 - @now.sec + 60*30*i
      @timelines << time.strftime("%H:%M")
      spaces.each_with_index do |space, j|
        is_empty = true
        space.reservations.each do |reservation|
          if reservation.start_time <= time && reservation.end_time >= time
            is_empty = false
          end
        end
        if is_empty
          @space_statuses[j] << "⬜️"
        else
          @space_statuses[j] << "⬛️"
        end
      end
    end
  end
end


private

  def reject_reservation
    redirect_to homes_reject_path unless current_user.status == true
  end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admin/reservations/index.html.erb
<div class="py-3 ml-5 h3">全予約一覧</div>
<div class="col-md-8 offset-md-1">
  <table class="table table-hover table-inverse">
  <thead>
      <th>予約日</th>
      <th>開始時間</th>
      <th>終了時間</th>
      <th>会員ID</th>
      <th>氏名</th>
      <th>（取消）</th>
      <th colspan="3"></th>
  </thead>

    <% @reservations.each do |reservation| %>
     <tr>
      <td><%= reservation.created_at.strftime(("%Y年%-m月%-d日 %H時%M分")) %></td>
      <td><%= reservation.start_time.strftime(("%Y年%-m月%-d日 %H時%M分")) %></td>
      <td><%= reservation.end_time.strftime(("%Y年%-m月%-d日 %H時%M分")) %></td>
      <td><%= reservation.user.id %></td>
      <td><%= reservation.user.full_name %></td>
      <td><%= link_to "取消", reservation_path(reservation), method: :delete, "data-confirm" => "予約を取消しますか？" %></td>
    <% end %>
    </table>
    <div class="mx-auto h5" style="width: 300px;"><%= paginate @reservations %></div>
    </div>
    

app/views/admin/reservations/show.html.erb
<h3>OOOさんの予約履歴一覧</h3>
<div class="col-md-8 offset-md-1">
  <table class="table table-hover table-inverse">
  <thead>
      <th>予約日</th>
      <th>席番号</th>
      <th>開始時間</th>
      <th>終了時間</th>
      <th>（取消）</th>
      <th colspan="3"></th>
  </thead>

    <% @reservations.each do |reservation| %>
     <tr>
      <td><%= reservation.created_at.strftime(("%Y年%-m月%-d日 %H時%M分")) %></td>
      <td><%= reservation.space_id %></td>
      <td><%= reservation.start_time.strftime(("%Y年%-m月%-d日 %H時%M分")) %></td>
      <td><%= reservation.end_time.strftime(("%Y年%-m月%-d日 %H時%M分")) %></td>
      <td><%= link_to "取消", reservation_path(reservation), method: :delete, "data-confirm" => "予約を取消しますか？" %></td>
    <% end %>
    </table>
    </div>