config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}

devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}  


  namespace :admin do
    get 'homes/top'
    resources :spaces
    resources :users
    resources :reservations, only: [:index, :show]
  end
  
  
# public_user
  get "/homes/reject" => "homes#reject", as: 'homes_reject'
  get "/users/quit" => "users#quit", as: 'users_quit'
  patch "/users/out" => "users#out", as: 'users_out' 
  root to: 'homes#top'
  resources :users, except: [:edit]
  resources :reservations # , except: [:show]
  post "/reservations/confirm" => "reservations#confirm", as: 'reservations_confirm'
  get 'homes/about'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>~Anyth~</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light" style= "background-color:#e8d3ca;"  >
        <div class="container">
          <a class="navbar-brand p-4" href="/">Anyth<p class="text-muted">〜AnytimeStuding〜</p></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
  <% if admin_signed_in? %>
    <li class="nav-item"><%= link_to "席一覧", admin_spaces_path, class: 'nav-link text-dark'  %></li>
    <li class="nav-item"><%= link_to "予約履歴一覧", admin_reservations_path, class: 'nav-link text-dark'  %></li>
    <li class="nav-item"><%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark'  %></li>
    <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark'  %></li>
    
  <% elsif user_signed_in? %>
    <li class="nav-item d-flex align-items-center"><%= current_user.last_name %>さんログイン中</li>
    <li class="nav-item"><%= link_to "予約画面", new_reservation_path, class: 'nav-link text-dark' %></li>
    <li class="nav-item"><%= link_to "マイページ", user_path(current_user), class: 'nav-link text-dark' %></li>
    <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %></li>
  

  <% else %>
    <li class="nav-item"><%= link_to 'About', homes_about_path, class: 'nav-link text-dark'  %></li>
    <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class: 'nav-link text-dark'  %></li>
    <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link text-dark'  %></li>
    
  <% end %>
              </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
      <footer class="text-white pt-5 pb-4" style= "background-color:#ccb9b1;">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>いつでも学習できる環境を提供</p>
            <%#= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">

            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
  
  
  
</html>